version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: chat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatdb"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  # Chat Service
  chat-service:
    build:
      context: ./chats-service
      dockerfile: Dockerfile
    container_name: chat-service
    restart: unless-stopped
    env_file:
      - ./chats-service/.env
    environment:
      # Override specific container settings
      NODE_ENV: production
      APP_HOST: 0.0.0.0
      APP_PORT: 3000
      # PostgreSQL Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password123
      DB_DATABASE: chatdb
      API_KEY: dev-api-key-2024
    ports:
      - "3002:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chat-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/chats-service/api/v1/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Documentation Hub
  documentation-hub:
    build:
      context: ./documentation-and-swagger
      dockerfile: Dockerfile
    container_name: documentation-hub
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - chat-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Chat Frontend
  chat-frontend:
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    restart: unless-stopped
    environment:
      # API Configuration
      REACT_APP_API_BASE_URL: http://localhost:3002/chats-service/api/v1
      REACT_APP_API_KEY: dev-api-key-2024
      # App Configuration
      REACT_APP_NAME: Smart Chat
      REACT_APP_VERSION: 1.0.0
      # Feature Flags
      REACT_APP_ENABLE_SMART_CHAT: true
      REACT_APP_AUTO_SAVE: true
      REACT_APP_ENABLE_FAVORITES: true
    ports:
      - "3003:3000"
    depends_on:
      - chat-service
    networks:
      - chat-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  postgres_data:
    driver: local

networks:
  chat-network:
    driver: bridge
